---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: cloud.aws_ops
        source: https://github.com/hakbailey/cloud.aws_ops.git
        type: git
        version: cloud-pattern-testing
      - name: amazon.aws
        source: https://github.com/ansible-collections/amazon.aws.git
        type: git
        version: main
  python:
    - boto3
    - botocore

images:
  base_image:
    name: docker.io/redhat/ubi9:latest

additional_build_steps:
  append_base: |
    RUN yum install -y git
