---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/aws:
      aws_region: "{{ aws_region }}"
  tasks:
    - name: Get AMIs for operating system and region
      amazon.aws.ec2_ami_info:
        filters:
          architecture: x86_64
          name: "{{ os_type }}*"
        owner:
          - amazon
      register: images

    - name: Set variables with dynamic values
      ansible.builtin.set_fact:
        image_id: "{{ (images.images | sort(attribute='name') | last).image_id }}"
        key_name: "{{ key_name | default(instance_name ~ '-key') }}"
        instance_tags: "{{ instance_tags | default('{}') | from_json }}"
        eip_tags: "{{ eip_tags | default('{}') | from_json }}"
        igw_tags: "{{ igw_tags | default('{}') | from_json }}"
        sg_name: "{{ sg_name | default(instance_name ~ '-external-sg') }}"
        sg_rule_names: "{{ sg_rules | map('split', ':') | map('first') | list }}"
        sg_tags: "{{ sg_tags | default('{}') | from_json }}"

    - name: Translate sg rules
      ansible.builtin.set_fact:
        selected_sg_rules: "{{ sg_rule_names | map('extract', sg_rule_options) | list }}"

    - name: Run ec2_instance_create role
      ansible.builtin.include_role:
        name: cloud.aws_ops.ec2_instance_create
      vars:
        ec2_instance_create_operation: create
        ec2_instance_create_aws_region: "{{ aws_region }}"
        ec2_instance_create_instance_name: "{{ instance_name }}"
        ec2_instance_create_instance_type: "{{ instance_type }}"
        ec2_instance_create_ami_id: "{{ image_id }}"
        ec2_instance_create_key_name: "{{ key_name }}"
        ec2_instance_create_vpc_id: "{{ vpc_id | default(omit) }}"
        ec2_instance_create_vpc_subnet_id: "{{ subnet_id | default(omit) }}"
        ec2_instance_create_tags: "{{ instance_tags | default(omit) }}"
        ec2_instance_create_wait_for_boot: "{{ wait_for_boot | bool }}"
        ec2_instance_create_associate_eip: "{{ associate_eip | bool }}"
        ec2_instance_create_eip_tags: "{{ eip_tags | default(omit) }}"
        ec2_instance_create_associate_igw: "{{ associate_igw | bool }}"
        ec2_instance_create_igw_tags: "{{ igw_tags | default(omit) }}"
        ec2_instance_create_associate_external_sg: "{{ associate_sg | bool }}"
        ec2_instance_create_external_sg_name: "{{ sg_name }}"
        ec2_instance_create_external_sg_description: "{{ sg_description }}"
        ec2_instance_create_external_sg_rules: "{{ selected_sg_rules }}"
